export {};
type RecorderState = { frozen: boolean; filter: "all" | "alarm" | "operation" };
const state: RecorderState = { frozen: false, filter: "all" };
function byId<T extends HTMLElement>(id: string): T | null { return document.getElementById(id) as T | null; }
function appendEvent(message: string): void { const log = byId<HTMLElement>("event-log"); if (!log) return; const row = document.createElement("p"); row.className = "instrumentation-event suite-event"; row.dataset.eventKind = "operation"; row.innerHTML = `<time>計装</time>${message}`; log.prepend(row); }
function classifyEventRows(): void { document.querySelectorAll<HTMLElement>("#event-log > *").forEach((row) => { if (row.dataset.eventKind) return; const text = row.textContent ?? ""; row.dataset.eventKind = /警報|異常|AZ-5|トリップ|高|低/.test(text) ? "alarm" : "operation"; }); }
function applyEventFilter(): void { classifyEventRows(); document.querySelectorAll<HTMLElement>("#event-log > *").forEach((row) => { row.hidden = state.filter !== "all" && row.dataset.eventKind !== state.filter; }); }
function lampTest(active: boolean): void { document.querySelectorAll<HTMLElement>(".annunciator").forEach((lamp) => lamp.classList.toggle("lamp-test-active", active)); }
function silenceHorn(): void { document.querySelectorAll<HTMLElement>(".annunciator.active").forEach((lamp) => lamp.classList.add("acknowledged")); const input = document.querySelector<HTMLInputElement>('[data-audio-volume="alarms"]'); if (input) { input.dataset.beforeSilence = input.value; input.value = "0"; input.dispatchEvent(new Event("input", { bubbles: true })); } appendEvent("警報音を停止（警報表示は保持）"); }
function restoreHorn(): void { const input = document.querySelector<HTMLInputElement>('[data-audio-volume="alarms"]'); if (!input) return; input.value = input.dataset.beforeSilence ?? "0.35"; input.dispatchEvent(new Event("input", { bubbles: true })); delete input.dataset.beforeSilence; appendEvent("警報音を復帰"); }
function freezeRecorder(): void { const canvas = byId<HTMLCanvasElement>("trend-canvas"); const panel = canvas?.closest<HTMLElement>(".trend-panel"); const image = byId<HTMLImageElement>("recorder-freeze-image"); if (!canvas || !panel || !image) return; state.frozen = !state.frozen; panel.classList.toggle("recorder-frozen", state.frozen); if (state.frozen) { image.src = canvas.toDataURL("image/png"); image.hidden = false; appendEvent("記録計表示をフリーズ"); } else { image.hidden = true; appendEvent("記録計表示を再開"); } const button = byId<HTMLButtonElement>("recorder-freeze"); if (button) button.textContent = state.frozen ? "記録再開" : "記録停止"; }
function updateCoreDiagnostics(): void { const cells = [...document.querySelectorAll<HTMLElement>("#core-map .core-cell")]; let maximum = -Infinity; let label = "--"; let count = 0; for (const cell of cells) { if (cell.classList.contains("inactive")) continue; const value = Number(cell.dataset.value ?? cell.title.match(/[-+]?\d+(?:\.\d+)?/)?.[0]); if (!Number.isFinite(value)) continue; count += 1; if (value > maximum) { maximum = value; label = cell.title.split("\n")[0] ?? `CH-${cell.dataset.index ?? "--"}`; } } const peak = byId("instrument-peak-value"); if (peak) peak.textContent = Number.isFinite(maximum) ? `${maximum.toFixed(2)} · ${label}` : "--"; const channelCount = byId("instrument-channel-count"); if (channelCount) channelCount.textContent = String(count); }
function install(): void { if (byId("instrumentation-console")) return; if (!document.querySelector(".bshch-shell")) { requestAnimationFrame(install); return; } const panel = document.createElement("aside"); panel.id = "instrumentation-console"; panel.className = "instrumentation-console collapsed"; panel.innerHTML = `<button id="instrumentation-toggle" class="instrumentation-toggle" aria-expanded="false">計装</button><div class="instrumentation-body"><header><strong>計装・記録盤</strong><span>補助監視</span></header><section class="instrumentation-diagnostics"><label>最大チャンネル<b id="instrument-peak-value">--</b></label><label>監視チャンネル数<b id="instrument-channel-count">0</b></label></section><section class="instrumentation-actions"><button id="lamp-test">ランプ試験</button><button id="horn-silence">警報音停止</button><button id="horn-restore">警報音復帰</button><button id="recorder-freeze">記録停止</button></section><label class="instrumentation-filter">履歴表示<select id="event-filter"><option value="all">すべて</option><option value="alarm">警報・異常</option><option value="operation">操作</option></select></label></div>`; document.body.append(panel); const trendPanel = document.querySelector<HTMLElement>(".trend-panel"); if (trendPanel) { const image = document.createElement("img"); image.id = "recorder-freeze-image"; image.className = "recorder-freeze-image"; image.alt = "停止中の記録計表示"; image.hidden = true; trendPanel.append(image); } byId("instrumentation-toggle")?.addEventListener("click", () => { const collapsed = panel.classList.toggle("collapsed"); byId("instrumentation-toggle")?.setAttribute("aria-expanded", String(!collapsed)); }); const lamp = byId<HTMLButtonElement>("lamp-test"); lamp?.addEventListener("pointerdown", () => lampTest(true)); for (const type of ["pointerup", "pointercancel", "pointerleave"] as const) lamp?.addEventListener(type, () => lampTest(false)); byId("horn-silence")?.addEventListener("click", silenceHorn); byId("horn-restore")?.addEventListener("click", restoreHorn); byId("recorder-freeze")?.addEventListener("click", freezeRecorder); byId<HTMLSelectElement>("event-filter")?.addEventListener("change", (event) => { state.filter = (event.currentTarget as HTMLSelectElement).value as RecorderState["filter"]; applyEventFilter(); }); const log = byId("event-log"); if (log) new MutationObserver(applyEventFilter).observe(log, { childList: true }); window.setInterval(updateCoreDiagnostics, 500); applyEventFilter(); }
queueMicrotask(install);
